DROP TABLE WORK_LOG 	CASCADE CONSTRAINTS; 
DROP TABLE ASSIGN       CASCADE CONSTRAINTS; 
DROP TABLE BILL         CASCADE CONSTRAINTS; 
DROP TABLE TASK_SKILL   CASCADE CONSTRAINTS; 
DROP TABLE SKILL        CASCADE CONSTRAINTS; 
DROP TABLE TASK       	CASCADE CONSTRAINTS; 
DROP TABLE PROJECT      CASCADE CONSTRAINTS; 
DROP TABLE EMP_SKILL    CASCADE CONSTRAINTS; 
DROP TABLE EMPLOYEE     CASCADE CONSTRAINTS; 
DROP TABLE CUSTOMER     CASCADE CONSTRAINTS; 
DROP TABLE REGION       CASCADE CONSTRAINTS; 

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY';




CREATE TABLE REGION (
  REGION_ID VARCHAR2(2),
  REGION_NAME VARCHAR2(255) NOT NULL,
  CONSTRAINT region_regionID_PK PRIMARY KEY (REGION_ID)
);

CREATE TABLE CUSTOMER (
  CUSTOMER_ID NUMBER(5),
  REGION_ID VARCHAR2(2),
  CUSTOMER_NAME VARCHAR2(255) NOT NULL,
  CUSTOMER_PHONE VARCHAR2(20) NOT NULL,
  CONSTRAINT customer_customerID_PK PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT customer_ID_FK FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID)
);

CREATE TABLE SKILL (
  SKILL_ID NUMBER PRIMARY KEY,
  SKILL_DESC VARCHAR2(255) NOT NULL,
  SKILL_RATE NUMBER(10,2) NOT NULL
);

CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID NUMBER PRIMARY KEY,
  REGION_ID VARCHAR2(2) NOT NULL,
  EMP_LNAME VARCHAR2(255) NOT NULL,
  EMP_MI CHAR(1) NOT NULL,
  EMP_FNAME VARCHAR2(255) NOT NULL,
  EMP_HIREDATE DATE NOT NULL,
  CONSTRAINT employee_region_FK FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID)
);

CREATE TABLE EMP_SKILL (
  EMPLOYEE_ID NUMBER NOT NULL,
  SKILL_ID NUMBER NOT NULL,
  CONSTRAINT emp_skill_pk PRIMARY KEY (EMPLOYEE_ID, SKILL_ID),
  CONSTRAINT emp_skill_employee_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
  CONSTRAINT emp_skill_skill_FK FOREIGN KEY (SKILL_ID) REFERENCES SKILL(SKILL_ID)
);



CREATE TABLE PROJECT (
  PROJ_ID NUMBER PRIMARY KEY,
  EMPLOYEE_ID NUMBER NOT NULL,
  CUSTOMER_ID NUMBER NOT NULL,
  PROJ_DATE DATE NOT NULL,
  PROJ_DESCRIPTION VARCHAR2(255) NOT NULL,
  PROJ_ESDATESTART DATE NOT NULL,
  PROJ_ESDATEEND DATE,
  PROJ_ESBUDGET NUMBER(10,2) NOT NULL,
  PROJ_ACDATESTART DATE,
  PROJ_ACDATEEND DATE,
  PROJ_ACCOST NUMBER(10,2),
  CONSTRAINT project_employee_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
  CONSTRAINT project_customer_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE TASK (
  TASK_ID NUMBER PRIMARY KEY,
  PROJ_ID NUMBER NOT NULL,
  TASK_DESCRIPTION VARCHAR2(255) NOT NULL,
  TBEGIN_DATE DATE NOT NULL,
  TEND_DATE DATE,
  CONSTRAINT task_project_FK FOREIGN KEY (PROJ_ID) REFERENCES PROJECT(PROJ_ID),
  CONSTRAINT task_dates_CK CHECK (TEND_DATE >= TBEGIN_DATE)
);

CREATE TABLE TASK_SKILL (
  TS_ID NUMBER PRIMARY KEY,
  TASK_ID NUMBER NOT NULL,
  SKILL_ID NUMBER NOT NULL,
  TS_QTY NUMBER NOT NULL,
  CONSTRAINT task_skill_task_FK FOREIGN KEY (TASK_ID) REFERENCES TASK(TASK_ID),
  CONSTRAINT task_skill_skill_FK FOREIGN KEY (SKILL_ID) REFERENCES SKILL(SKILL_ID),
  CONSTRAINT task_skill_qty_CK CHECK (TS_QTY > 0)
);


CREATE TABLE BILL (
  BILL_ID NUMBER PRIMARY KEY,
  PROJ_ID NUMBER NOT NULL,
  BILL_DATE DATE NOT NULL,
  CONSTRAINT bill_project_FK FOREIGN KEY (PROJ_ID) REFERENCES PROJECT(PROJ_ID)
);


CREATE TABLE ASSIGN (
  ASSIGN_ID NUMBER PRIMARY KEY,
  EMPLOYEE_ID NUMBER NOT NULL,
  TS_ID NUMBER NOT NULL,
  ABEGIN_DATE DATE,
  AEND_DATE DATE,
  CONSTRAINT assign_employee_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
  CONSTRAINT assign_task_skill_FK FOREIGN KEY (TS_ID) REFERENCES TASK_SKILL(TS_ID),
  CONSTRAINT assign_dates_CK CHECK (AEND_DATE >= ABEGIN_DATE)
);

CREATE TABLE WORK_LOG (
  WL_ID NUMBER PRIMARY KEY,
  ASSIGN_ID NUMBER NOT NULL,
  BILL_ID NUMBER NOT NULL,
  WL_DATE DATE NOT NULL,
  WL_HOURS NUMBER(4,2) NOT NULL,
  CONSTRAINT work_log_assign_FK FOREIGN KEY (ASSIGN_ID) REFERENCES ASSIGN(ASSIGN_ID),
  CONSTRAINT work_log_bill_FK FOREIGN KEY (BILL_ID) REFERENCES BILL(BILL_ID),
  CONSTRAINT work_log_hours_CK CHECK (WL_HOURS >= 0)
);

